import { Poppins, Volkhov, Open_Sans } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import links from "./NavLinks";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

const volkhov = Volkhov({
  subsets: ["latin"],
  variable: "--font-volkhov",
  weight: "400",
});

const open_sans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open_sans",
  weight: "400",
});

export const metadata = {
  title: "Jadoo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${volkhov.variable} ${open_sans.variable} overflow-x-hidden`}>
        <nav className="container mx-auto w-5/6 flex justify-between py-8 items-center">
          <Image src={"/logo.png"} alt="logo" width={92} height={64}/>

          {/* urls */}
          <ul className="flex space-x-14 font-medium">
            {
              links.map(link => (
                <li key={link.id}>
                  <Link href={"#"}>{link.title}</Link>
                </li>
              ))
            }

            <li><Link href={"#"} className="flex items-center">EN &nbsp; <Image src="/arrow.svg" alt="select language" width={8} height={8} /></Link></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
